interface Env { STEPFUN_API_KEY: string; ALLOWED_ORIGIN?: string; CARD_COPY_DAILY_LIMIT?: string; CARD_ART_DAILY_LIMIT?: string; USAGE_LIMITER: DurableObjectNamespace; }
const json = (body: unknown, status = 200, origin = '*') => new Response(JSON.stringify(body), { status, headers: { 'content-type': 'application/json; charset=utf-8', 'access-control-allow-origin': origin, 'access-control-allow-methods': 'GET,POST,OPTIONS', 'access-control-allow-headers': 'content-type' } });
function validId(id: unknown): id is string { return typeof id === 'string' && /^[a-zA-Z0-9_-]{16,128}$/.test(id); }
async function readBody(request: Request) { const text = await request.text(); if (text.length > 64 * 1024) throw new Error('PAYLOAD_TOO_LARGE'); return JSON.parse(text || '{}'); }
async function upstream(env: Env, path: string, payload: object) { if (!env.STEPFUN_API_KEY) throw new Error('MISSING_SERVER_KEY'); const response = await fetch(`https://api.stepfun.com/v1/${path}`, { method: 'POST', headers: { authorization: `Bearer ${env.STEPFUN_API_KEY}`, 'content-type': 'application/json' }, body: JSON.stringify(payload), signal: AbortSignal.timeout(75_000) }); if (response.status === 429) throw new Error('UPSTREAM_RATE_LIMITED'); if (!response.ok) throw new Error(`UPSTREAM_${response.status}`); return response.json<any>(); }
async function handle(request: Request, env: Env, origin: string) {
  if (request.method === 'OPTIONS') return json({}, 204, origin);
  const url = new URL(request.url); if (request.method === 'GET' && url.pathname === '/health') return json({ ok: true }, 200, origin);
  if (request.method !== 'POST' || !['/api/cards/copy', '/api/cards/art'].includes(url.pathname)) return json({ code: 'NOT_FOUND', message: 'Not found' }, 404, origin);
  let body: any; try { body = await readBody(request); } catch (error: any) { return json({ code: error.message === 'PAYLOAD_TOO_LARGE' ? 'PAYLOAD_TOO_LARGE' : 'INVALID_JSON', message: 'Invalid request' }, 400, origin); }
  if (!validId(body.deviceId)) return json({ code: 'INVALID_DEVICE_ID', message: 'Invalid device id' }, 400, origin);
  const kind = url.pathname.endsWith('/copy') ? 'copy' : 'art'; const limit = Number(kind === 'copy' ? env.CARD_COPY_DAILY_LIMIT || 20 : env.CARD_ART_DAILY_LIMIT || 5); const valid = kind === 'copy' ? Array.isArray(body.sourceTasks) && body.sourceTasks.length > 0 && body.sourceTasks.length <= 50 && body.sourceTasks.every((task: unknown) => typeof task === 'string' && task.length <= 200) : typeof body.name === 'string' && body.name.length <= 100 && typeof body.description === 'string' && body.description.length <= 500;
  if (!valid) return json({ code: 'INVALID_INPUT', message: 'Invalid card input' }, 400, origin);
  const id = env.USAGE_LIMITER.idFromName(`${new Date().toISOString().slice(0, 10)}:${kind}:${body.deviceId}:${request.headers.get('CF-Connecting-IP') || 'unknown'}`); if (!(await env.USAGE_LIMITER.get(id).fetch(`https://limiter/check?limit=${limit}`)).ok) return json({ code: 'RATE_LIMITED', message: '今日 AI 额度已用完' }, 429, origin);
  try { if (kind === 'copy') { const result = await upstream(env, 'chat/completions', { model: 'step-3.7-flash', messages: [{ role: 'system', content: '你是离谱发明所的卡牌文案生成器。卡牌名称4-10个汉字，描述40-80字，只输出JSON：{"name":"名称","description":"描述"}。' }, { role: 'user', content: `今日完成任务：${body.sourceTasks.join('、')}` }], temperature: 1, max_tokens: 1000 }); const content = result.choices?.[0]?.message?.content || ''; const start = content.indexOf('{'); const end = content.lastIndexOf('}'); if (start < 0 || end <= start) throw new Error('INVALID_UPSTREAM_RESPONSE'); return json(JSON.parse(content.slice(start, end + 1)), 200, origin); } const result = await upstream(env, 'images/generations', { model: 'step-image-edit-2', prompt: `Square illustration. STRICTLY NO TEXT, NO LETTERS, NO WORDS, NO CHINESE CHARACTERS, NO TITLES, NO LABELS anywhere in the image. Pure scene artwork only. Theme inspired by "${body.name}" (${body.description}). Dark blue lab background, steampunk machinery in center, neon glowing tubes, sci-fi atmosphere. No card frame, no card border.`, n: 1, size: '1024x1024', response_format: 'b64_json' }); const imageBase64 = result.data?.[0]?.b64_json; if (!imageBase64) throw new Error('INVALID_UPSTREAM_RESPONSE'); return json({ imageBase64, mimeType: 'image/png' }, 200, origin); } catch (error: any) { const code = error.message === 'MISSING_SERVER_KEY' ? 'SERVICE_NOT_CONFIGURED' : error.message.includes('RATE_LIMITED') ? 'UPSTREAM_RATE_LIMITED' : 'AI_SERVICE_ERROR'; return json({ code, message: 'AI 服务暂不可用' }, 502, origin); }
}
export default { async fetch(request: Request, env: Env) { const requested = request.headers.get('Origin') || ''; const origin = requested === (env.ALLOWED_ORIGIN || '') || requested === 'http://127.0.0.1:1420' ? requested : env.ALLOWED_ORIGIN || ''; return handle(request, env, origin); } };
export class UsageLimiter { constructor(private state: DurableObjectState) {} async fetch(request: Request) { const current = (await this.state.storage.get<number>('count')) || 0; const limit = Number(new URL(request.url).searchParams.get('limit') || 1); if (current >= limit) return new Response('limited', { status: 429 }); await this.state.storage.put('count', current + 1); return new Response('ok'); } }
